### ISSUE TITLE
jitsi-keycloak-adapter doesn't work on jitsi-meet-electorn

### ISSUE THREAD

**Issue by CreepyJ** [nordeck/jitsi-keycloak-adapter#6] opened 2023-12-11 02:21 UTC
**Describe the bug**

I deployed the Jitsi Keycloak adapter, and it works fine on the web, but encounters issues on Jitsi Meet Electron. 
I can't join any meeting room.
Can you add support for Jitsi Meet Electron?

**Steps To Reproduce**

1. deploy Jitsi Keycloak adapter
2. join a meeting on Jitsi Meet Electron

**Expected behavior**

Get in a meeting room

**Comment by emrahcom** [comment] 2023-12-12 07:53
Hi @CreepyJ, thank you for reporting the issue.

After some investigations, looks like the issue is related with Electron limitations and nothing to do on `jitsi-keycloak-adapter`. Any recommendations or PR are welcome.

**Comment by emrahcom** [comment] 2024-01-03 12:18
Hi @CreepyJ,

I created a [PR](https://github.com/jitsi/jitsi-meet-electron/pull/938) on `jitsi-meet-electron` repo which fixes the issue.

**Comment by emrahcom** [comment] 2024-01-03 14:43
PR is merged and it is fixed for the upcoming release of  `jitsi-meet-electron`

**Closed by emrahcom** 2024-01-03 14:43 UTC
Labels: bug
